### ISSUE TITLE
MCU family target to inherit from for this target?

### ISSUE THREAD

**Issue by 0xc0170** [ARMmbed/target-efm32hg-stk-gcc#1]
I noticed that this target inherits from mbed-gcc only. If there's a user with own board, using the same mcu as it's on happy gecko, how to derive a new target? This might be a case for any efm32 targets out there?

An example, frdm-k64f inherits from kinetis k64f: https://github.com/ARMmbed/target-frdm-k64f-gcc/blob/master/target.json#L5

**Comment by asmellby** [comment]
Fixed by e8e14ce.
